Lucky_Draw_Promotion/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult LoginAdmin()
        {
            return View();
        }
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpGet]
        public ActionResult RecoverPassword()
        {
            return View();
        }
    }
}

Lucky_Draw_Promotion/Controllers/CustomerController.cs
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoginUser()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        public ActionResult OTPConfirm()
        {
            return View();
        }

        public ActionResult NewPassword()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }
    }
}

Lucky_Draw_Promotion/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lucky_Draw_Promotion/Controllers/LandingPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class LandingPageController : Controller
    {
        // GET: LandingPage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LandingPage()
        {
            return View();
        }

        public ActionResult SpinPrizeWheel()
        {
            return View();
        }

        public ActionResult DeliveredAddress()
        {
            return View();
        }

        public ActionResult WinnersList()
        {
            return View();
        }

        public ActionResult YourGiftsList()
        {
            return View();
        }

        public ActionResult Profile()
        {
            return View();
        }
    }
}

Lucky_Draw_Promotion/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult CampaignManagement()
        {
            return View();
        }

        public ActionResult CreateCampaignProgramSize()
        {
            return View();
        }

        public ActionResult CreateCampaignTimeFrame()
        {
            return View();
        }

        public ActionResult CreateCampaignGifts()
        {
            return View();
        }

        public ActionResult CreateCampaignRulesForGifts()
        {
            return View();
        }

        public ActionResult CreateCampaignSummary()
        {
            return View();
        }

        public ActionResult ListOfGeneratedGifts()
        {
            return View();
        }

        public ActionResult GiftsCategory()
        {
            return View();
        }

        public ActionResult Customer()
        {
            return View();
        }
    }
}

Lucky_Draw_Promotion/Controllers/ManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lucky_Draw_Promotion.Controllers
{
    public class ManageController : Controller
    {
        // GET: Manage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageDashboard()
        {
            return View();
        }

        public ActionResult ManageBarcodes()
        {
            return View();
        }

        public ActionResult GenerateNewBarcodes()
        {
            return View();
        }

        public ActionResult Code_Detail()
        {
            return View();
        }

        public ActionResult ManageBarcodeHistory()
        {
            return View();
        }

        public ActionResult ManageGifts()
        {
            return View();
        }

        public ActionResult AddNewGiftsCode()
        {
            return View();
        }

        public ActionResult ManageRulesForGift()
        {
            return View();
        }

        public ActionResult AddNewRules()
        {
            return View();
        }

        public ActionResult ManageWinner()
        {
            return View();
        }

        public ActionResult ManageSetting()
        {
            return View();
        }
    }
}

Lucky_Draw_Promotion/Views/Admin/LoginAdmin.cshtml
@model Lucky_Draw_Promotion.Models.ADMIN

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login Admin</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5"> 
                                <div id="over">
                                    <img src="~/Images/icons8-user-64 (1).png" />
                                </div>
                                <div class="card-header">
                                    <h3 style="font-weight:bold; text-align: center">Login</h3>
                                </div>
                                <div class="card-body">
                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()

                                        <div class="form-horizontal">
                                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                            <div class="form-group">
                                                <label class="small mb-1" for="inputEmailAddress">Email</label>
                                                @Html.TextBoxFor(model => model.EMAIL, new { @class = "form-control py-4", @autofocus = "autofocus", @placeholder = "Nhập email" })
                                            </div>

                                            <div class="form-group">
                                                <label class="small mb-1" for="inputPassword">Mật khẩu</label>
                                                @Html.PasswordFor(model => model.PASSWORD, new { @class = "form-control py-4", @placeholder = "Nhập mật khẩu" })
                                            </div>
                                        </div>
                                    }
                                </div>
                                <div class="card-footer text-center">
                                    <button id="btn-login1">
                                        Login
                                    </button>
                                    <br /><br />
                                    <div style="color:blue"><a href="@Url.Action("ForgotPassword","Admin")"><u>Forgot password?</u></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

Lucky_Draw_Promotion/Views/Customer/ForgotPassword.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Forgot Password</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div id="layout-customer">
        <div><img src="~/Images/unilever-logo.png" style="width: 100%;" /></div>
        <br />
        <div class="login-user">
            <div style="font-weight: bold; text-align: center">Nhập số điện thoại để đặt lại mật khẩu</div>
            <br />
            <div class="input-box">
                <input type="text" name="phone" placeholder="Nhập số điện thoại" class="col-md-12 py-2" />
            </div>
            <br /><br />
            <button id="btn-submit">Gửi</button>
            <br /><br /><br />
            <div style="text-align: center;"><a href="@Url.Action("LoginUser","Customer")" style="color: darkorange"><u>Đăng nhập</u></a></div>
        </div>
    </div>
</body>
</html>

Lucky_Draw_Promotion/Views/Customer/LoginUser.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div id="layout-customer">
        <div><img src="~/Images/unilever-logo.png" style="width: 100%;"/></div>
        <br />
        <div class="login-user">
            <div class="input-box">
                <input type="text" name="phone" placeholder="Số điện thoại" class="col-md-12 py-2" />
            </div>    
            <br />
            <div class="input-box">
                <input type="password" name="password" placeholder="Mật khẩu" id="myPassword" class="col-md-12 py-2" />
                <span class="eye" onclick="myFunction()">
                    <i id="hide1" class="fas fa-eye"></i>
                    <i id="hide2" class="fas fa-eye-slash"></i>
                </span>
            </div>
            <br />
            <a href="@Url.Action("ForgotPassword","Customer")" style="color: darkorange;"><u>Quên mật khẩu?</u></a>
            <br /><br />
            <button id="btn-dangnhap">Đăng nhập</button>
            <br /><br />
            <div style="text-align: center">
                <a href="@Url.Action("Register","Customer")" style="color: darkorange;"><u>Đăng ký</u></a>
            </div>
        </div>       
    </div>

    <script>
        function myFunction() {
            var x = document.getElementById("myPassword");
            var y = document.getElementById("hide1");
            var z = document.getElementById("hide2");

            if (x.type === 'password') {
                x.type = "text";
                y.style.display = "block";
                z.style.display = "none";
            }

            else {
                x.type = "password";
                y.style.display = "none";
                z.style.display = "block";
            }
        }
    </script>
</body>
</html>

Lucky_Draw_Promotion/Views/Customer/NewPassword.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>New Password</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div id="layout-customer">
        <div><img src="~/Images/unilever-logo.png" style="width: 100%;" /></div>
        <br />
        <div class="login-user">
            <div style="font-weight: bold; text-align: center">Đổi mật khẩu</div>
            <br />
            <div class="input-box">
                <input type="password" name="password" placeholder="Nhập mật khẩu mới" class="col-md-12 py-2" />
            </div>
            <br />
            <div class="input-box">
                <input type="password" name="password" placeholder="Nhập lại mật khẩu" class="col-md-12 py-2" />
            </div>
            <br /><br />
            <button id="btn-submit">Xác nhận</button>
            <br /><br /><br />
            <div style="text-align: center;"><a href="@Url.Action("LoginUser","Customer")" style="color: darkorange"><u>Đăng nhập</u></a></div>
        </div>
    </div>
</body>
</html>

Lucky_Draw_Promotion/Views/Customer/OTPConfirm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>OTP Confirm</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div id="layout-customer">
        <div><img src="~/Images/unilever-logo.png" style="width: 100%;" /></div>
        <br />
        <div class="login-user">
            <div style="font-weight: bold; text-align: center">Đổi mật khẩu</div>
            <br />
            <div class="input-box">
                <input type="text" name="phone" placeholder="Nhập mã OTP" class="col-md-12 py-2" />
            </div>
            <br />
            <div style="font-weight: bold; text-align: center">Mã OTP sẽ bị vô hiệu lực trong 59 giây</div>
            <br />
            <div style="text-align: center; font-weight: bold;"><a href="#" style="color: darkorange;"><u>Gửi lại</u></a></div>
            <br /><br />
            <button id="btn-submit">Xác nhận</button>
            <br /><br /><br />
            <div style="text-align: center;"><a href="@Url.Action("ForgotPassword","Customer")" style="color: darkorange"><u>Quay lại</u></a></div>
        </div>
    </div>
</body>
</html>

Lucky_Draw_Promotion/Views/Customer/Register.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Register</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body>
    <div id="register">
        <div><img src="~/Images/unilever-logo.png" style="width: 100%;" /></div>
        <br />
        <div class="register-user">
            <div style="font-weight: bold; text-align: center">Đăng ký</div>

            <div class="input-box">
                <input type="text" name="fullname" placeholder="Họ và tên" class="col-md-12 py-2" />
            </div>

            <div class="input-box">
                <input type="text" name="phone" placeholder="Số điện thoại" class="col-md-12 py-2" />
            </div>

            <div class="input-box">
                <input type="text" name="birth" placeholder="Ngày sinh" class="col-md-12 py-2" />
            </div>

            <div class="input-box">
                <select class="col-md-12 py-2" style="border-style: none;">
                    <option disabled selected>Chức vụ</option>
                    <option>Giám đốc</option>
                </select>
            </div>

            <div class="input-box">
                <select class="col-md-12 py-2" style="border-style: none;">
                    <option disabled selected>Loại hình kinh doanh</option>
                    <option>Nhà hàng</option>
                </select>
            </div>

            <div class="input-box">
                <input type="password" name="password" placeholder="Mật khẩu" class="col-md-12 py-2" />
            </div>
            <br />
            <div>
                <input type="checkbox" name="check" placeholder="" />&ensp;Tôi xác nhận tôi trên 16 tuổi.
            </div>
            <br />
            <div>
                <input type="checkbox" name="check" placeholder="" />&ensp;Tôi đồng ý nhận các thông tin khuyến mại, quảng cáo, khảo sát và chăm sóc khách hàng của Unilever.
            </div>
            <br />
            <div>
                <input type="checkbox" name="check" placeholder="" />&ensp;Tôi đã đọc thông báo về quyền riêng tư của Unilever <u><a href="#" style="color: orange;">tại đây</a></u>.
            </div>
            <br /><br />
            <button id="btn-register">Đăng ký</button>
            <br /><br />
            <div style="text-align: center;"><a href="@Url.Action("LoginUser","Customer")" style="color: darkorange"><u>Đăng nhập</u></a></div>
        </div>
    </div>
</body>
</html>

Lucky_Draw_Promotion/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Lucky_Draw_Promotion/Views/Main/CampaignManagement.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Campaign Management</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body style="background-color: #ccccff">
    <div>
        <div id="menu">
            <ul>
                <li><img src="~/Images/logo.png" width="64" height="64" /></li>
                <li><a href="@Url.Action("Dashboard","Main")"><i class="fas fa-home"></i><br />Dashboard</a></li>
                <li><a href="@Url.Action("CampaignManagement","Main")"><i class="fas fa-tags"></i><br />Campaign</a></li>

                <li>
                    <a href="#"><i class="fas fa-gift"></i><br />Gift <i class="fas fa-caret-down"></i></a>
                    <ul>
                        <li><a href="@Url.Action("ListOfGeneratedGifts","Main")">List of Generated Gifts</a></li>
                        <li><a href="@Url.Action("GiftsCategory","Main")">Gifts Category</a></li>
                    </ul>
                </li>

                <li><a href="#"><i class="fas fa-user"></i><br />Customer</a></li>
                <li><a href="#"><i class="fas fa-gear"></i><br />Setting</a></li>
            </ul>
        </div>
        <div class="search-text">
            <input type="search" name="Tìm kiếm" placeholder="Search..." />
            <a href="#" class="search-button">
                <i class="fas fa-search"></i>
            </a>
        </div>
        <div id="title1">
            <h6>&nbsp;<i class="fas fa-home"><span style="color:#6600cc"> Dashboard</span>&nbsp;/ Campaigns Management</i></h6>
        </div>

        <div id="B">
            <div id="title2">
                <h5>&nbsp;<i class="fas fa-tags"> Campaigns</i></h5>
            </div>
            <div id="createcp">
                <a href="@Url.Action("CreateCampaignProgramSize","Main")" style="color: #ff3333"><i class="fas fa-plus-circle fa-2x"></i></a>
            </div>
        </div>
        <br />
        <div id="filter">
            <select id="select2">
                <option>Match all filters</option>
                <option>Match any filters</option>
            </select>
            <br />
            <select id="select3">
                <option disabled selected>Search criteria</option>
                <option>Campaign Name</option>
                <option>Create Date</option>
                <option>Expired Date</option>
            </select>
            <br />
            <select id="select4">
                <option disabled selected>Condition...</option>
                <option id="opt1">Program type is Gift Card</option>
                <option id="opt2">Start date is more than 1 month</option>
            </select>
            <br />
            <div id="text5">
                <input type="text" name="value" placeholder="Value" class="col-md-12 py-2" />
            </div>
            
            <div>
                <button id="btnAdd">
                    <i class="fas fa-plus"></i> Add
                </button>
            </div>
        </div>
        <div id="filter-cdt">
            <div id="reload">
                <button id="btnReload">Reload</button>
            </div>
        </div>
        <br /><br />
        <div id="D">
            <div id="title3">
                <div>Name</div>
                <div>Start Date</div>
                <div>Expired Date</div>
                <div>Activated Code</div>
                <div>Gifts Quantity</div>
                <div>Scanned</div>
                <div>Used for spin</div>
                <div>Win</div>
            </div>
            <hr />
            <div id="data-campaign-list">
                <div style="font-weight: bold">
                    &ensp;<i class="fas fa-unlock"></i>&nbsp;<u><span style="color: blueviolet">Lucky Draw 1</span></u>
                    <br />
                    &ensp;<i class="fas fa-paper-plane"></i>&nbsp;Active
                </div>
                <div>&ensp;02/08/2020 <br /> &ensp;23:59:49</div>
                <div>&emsp;-</div><br />
                <div style="color:#b3b3ff">&emsp;<u>200.000</u></div><br />
                <div>&emsp;1.500</div><br />
                <div>&emsp;50</div><br />
                <div>&emsp;20</div><br />
                <div>&emsp;10</div><br />
            </div>
            <hr />
            <div id="data-campaign-list">
                <div style="font-weight: bold">
                    &ensp;<i class="fas fa-unlock"></i>&nbsp;<span>Lucky Draw 2</span>
                    <br />
                    &ensp;<i class="fas fa-paper-plane"></i>&nbsp;Active
                </div>
                <div>&ensp;02/08/2020 <br /> &ensp;23:59:49</div>
                <div>&emsp;-</div><br />
                <div style="color:#b3b3ff">&emsp;<u>200.000</u></div><br />
                <div>&emsp;1.000</div><br />
                <div>&emsp;0</div><br />
                <div>&emsp;0</div><br />
                <div>&emsp;20</div><br />
            </div>
        </div>
        <div id="footer">
            <div>
                Show <select style="width: 50px"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option></select> <i>entries</i>
            </div>
            <div><i>Showing 1 to 2 of 2 entries</i></div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

Lucky_Draw_Promotion/Views/Main/CreateCampaignGifts.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Create Campaign: Gifts</title>
    <link href="~/Content/styles.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
</head>
<body style="background-color: #ccccff">
    <div>
        <div id="menu">
            <ul>
                <li><img src="~/Images/logo.png" width="64" height="64" /></li>
                <li><a href="@Url.Action("Dashboard","Main")"><i class="fas fa-home"></i><br />Dashboard</a></li>
                <li><a href="@Url.Action("CampaignManagement","Main")"><i class="fas fa-tags"></i><br />Campaign</a></li>
                <li><a href="#"><i class="fas fa-gift"></i><br />Gift</a></li>
                <li><a href="#"><i class="fas fa-user"></i><br />Customer</a></li>
                <li><a href="#"><i class="fas fa-gear"></i><br />Setting</a></li>
            </ul>
        </div>
        <div class="search-text">
            <input type="search" name="Tìm kiếm" placeholder="Search..." />
            <a href="#" class="search-button">
                <i class="fas fa-search"></i>
            </a>
        </div>
        <div id="title1">
            <h6>&nbsp;<i class="fas fa-home"><span style="color:#6600cc"> Dashboard&nbsp;/ Campaign </span>/ Create New Campaign</i></h6>
        </div>

        <div id="B">
            <div id="title2">
                <h5>&nbsp;<i class="fas fa-tags"> Create New Campaign</i></h5>
            </div>
        </div>
        <div id="title-campaign">3. Gifts</div>
        <div class="data-new-campaign">
            <div id="start-date">Information</div>
            <br />
            <select id="select-product">
                <option disabled selected>Select a product</option>
                <option>Bột nêm Hải Sản</option>
                <option>Bột xốt nâu Demi</option>
                <option>Bột xốt nêm đậm đặc thịt gà</option>
            </select>
            <br /><br />
            <div id="txt-description2">
                <input type="text" name="description" placeholder="Description" class="col-md-12 py-2"/>
            </div>
            <br /><br />
            <div>&emsp;Gift code count*</div>
            <div id="gift-code-count">
                <input type="text" name="gift-code-count" placeholder="" class="col-md-4 py-2" style="border-style: none;" />
            </div>
        </div>

        <div id="name-campaign">New Campaign</div>
        <div class="list-new-campaign">
            <button id="btnNumber">1</button>&emsp;&emsp;Program size <br />
            <button id="btnNumber">2</button>&emsp;&emsp;Time frame <br />
            <button id="btnNumber1">3</button>&emsp;&emsp;<span style="color: #993399; font-weight: bold">Gifts</span> <br />
            <button id="btn-next-step-1">
                <a href="#" style="text-decoration: none; color: #fff">Next step</a>
            </button>
            <br /><br />
            <button id="btnNumber">4</button>&emsp;&emsp;Rules for gifts <br />
            <button id="btnNumber">5</button>&emsp;&emsp;Summary <br />
            <hr />
            <button id="cancel"><img src="~/Images/icons8-xbox-x-24.png" /> Cancel</button>
            <button id="save-draft">Save draft</button>
        </div>
    </div>
</body>
</html>